### ISSUE TITLE
Any documentation to get started?

### ISSUE THREAD

**Issue by darrinlrogers** [ZJoscha/PyWSC#1]
Hi. I just stumbled across this in a moodle.org post from 2017. I realize this might not work as-is right now, and that's okay. I'm a beginner with Python but motivated to make this work to make my moodle grade workflow doable. If you have any "getting started" or "how to proceed" type files, I'd love to see them, even if they are incomplete.

**Comment by ZJoscha** [comment]
Hi, this project was my bachelor thesis - i could provide the manual written in german, maybe it helps...

**Comment by ZJoscha** [comment]
@darrinlrogers : here you go
[Handbuch PyWSC.pdf](https://github.com/ZJoscha/PyWSC/files/10699138/Handbuch.PyWSC.pdf)

**Comment by ZJoscha** [comment]
@darrinlrogers Here you go. 
[PyWSCHandbuch.pdf](https://github.com/ZJoscha/PyWSC/files/10700454/PyWSCHandbuch.pdf)

**Comment by darrinlrogers** [comment]
Thank you! My German is quite bad, but Google Translate exists :)

**Comment by ZJoscha** [comment]
closed until further support is requested
